### ISSUE TITLE
HSSelect with search + API

### ISSUE THREAD

**Issue by brcebn** [htmlstreamofficial/preline#677]
### Summary

Submit skips the selected values

### Steps to Reproduce

```
<select name="establishments[]" multiple="" data-hs-select='{
                        "wrapperClasses": "relative pe-9 min-h-11.5 flex items-center flex-wrap w-full border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-neutral-900 dark:border-neutral-700 ps-8",
                    "apiUrl": "<%= department_establishments_path(@department.code, format: :json) %>",
                        "apiQuery": "limit=10",
                        "apiSearchQueryKey": "q",
                        "apiSelectedValues": ["bulbasaur", "ivysaur", "venusaur"],
                        "apiDataPart": "establishments",
                        "apiFieldsMap": {
                          "id": "uai",
                          "val": "uai",
                          "title": "name"
                        },
                    "mode": "tags",
                        "toggleTag": "<button type=\"button\" class=\"h-full\" aria-expanded=\"false\"></button>",
                        "tagsInputId": "hs-tags-input",
                        "hasSearch": "true",
    "tagsInputClasses": "py-1.5 px-3 rounded-lg order-1 border-transparent focus:ring-0 text-sm outline-hidden dark:bg-neutral-900 dark:placeholder-neutral-500 dark:text-neutral-400 w-full",
    "tagsItemTemplate": "<div class=\"flex flex-nowrap items-center text-nowrap relative z-10 bg-gray-100 rounded-sm p-1 m-1 dark:bg-neutral-700\"><div class=\"whitespace-nowrap text-gray-800 dark:text-neutral-200\" data-title=\"\"></div><div class=\"inline-flex shrink-0 justify-center items-center size-5 ms-6 rounded-md text-gray-800 hover:bg-gray-200 focus:outline-hidden focus:ring-2 focus:ring-gray-400 text-sm cursor-pointer dark:bg-neutral-700 dark:text-neutral-200 dark:hover:bg-neutral-600 dark:focus:bg-neutral-600\" data-remove=\"true\"><!-- BEGIN app/components/icon_component.html.erb --><svg aria-hidden=\"true\" fill=\"currentColor\" viewbox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\" class=\"shrink-0 size-3\">\n  <path fill-rule=\"evenodd\" d=\"M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z\" clip-rule=\"evenodd\"></path>\n</svg>\n\n\n<!-- END app/components/icon_component.html.erb --></div></div>",
                    "toggleTag": "<button type=\"button\" class=\"w-99\" aria-expanded=\"false\"></button>",
                    "toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 ps-4 pe-9 flex gap-x-2 text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:outline-hidden focus:ring-2 focus:ring-blue-500 dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400 dark:focus:outline-hidden dark:focus:ring-1 dark:focus:ring-neutral-600",
                    "dropdownClasses": "mt-2 z-50 w-full max-h-72 p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-track]:bg-gray-100 [&::-webkit-scrollbar-thumb]:bg-gray-300 dark:[&::-webkit-scrollbar-track]:bg-neutral-700 dark:[&::-webkit-scrollbar-thumb]:bg-neutral-500 dark:bg-neutral-900 dark:border-neutral-700",
                    "optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-900 dark:hover:bg-neutral-800 dark:text-neutral-200 dark:focus:bg-neutral-800",
                    "optionTemplate": "<div class=\"flex items-center\"><div class=\"me-2\" data-icon></div><div><div class=\"hs-selected:font-semibold text-sm text-gray-800 dark:text-neutral-200 \" data-title></div></div><div class=\"ms-auto\"><span class=\"hidden hs-selected:block\"><svg class=\"shrink-0 size-4 text-blue-600\" xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\"><path d=\"M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z\"/></svg></span></div></div>",
                    "extraMarkup": "<div class=\"absolute top-1/2 end-3 -translate-y-1/2\"><svg class=\"shrink-0 size-3.5 text-gray-500 dark:text-neutral-500 \" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m7 15 5 5 5-5\"/><path d=\"m7 9 5-5 5 5\"/></svg></div>"
                    }' class="hidden">
      </select>
```

### Demo Link

nolink.com

### Expected Behavior

Selected values form the select should be send regardless of the configuration. 

### Actual Behavior

With `"hasSearch": "true",` form does not send the selected values. 
Without, values are send correctly. 

### Screenshots

# With `"hasSearch": "true",`

<img width="1734" height="50" alt="Image" src="https://github.com/user-attachments/assets/8aad9cdb-bd9e-4562-b333-044d7bc8becb" />

# Without `"hasSearch": "true",`
<img width="2620" height="58" alt="Image" src="https://github.com/user-attachments/assets/2c45c603-a92c-4fb9-b8dd-9c7c0bd56f27" />

**Comment by benebrice** [comment]
Issue isolated. 

This code block is causing troubles. It wasn't there on version `2.7.0`

```
// searchOptions
// Removed during the test
if (val.length <= this.minSearchLength) {
	const res = await this.apiRequest(«);
	this.remoteOptions = res;

	Array.from(this.dropdown.querySelectorAll("[data-value]")).forEach((el) =>
		el.remove()
	);
	Array.from(this.el.querySelectorAll("option[value]")).forEach(
		(el: HTMLOptionElement) => {
			el.remove();
		},
	);

	if (res.length) this.buildOptionsFromRemoteData(res);
	else console.log("No data responded!");

	return false;
}
```

And also this one:

```
// selectMultipleItems
// Only the JS property of the DOM is updated
// But it select is hidden (this case), browser (safari in my case) can ignore those properties on submit
Array.from(this.el.children)
			.filter((el) => this.value.includes((el as HTMLOptionElement).value))
			.forEach((el) => ((el as HTMLOptionElement).selected = true));

// Changed to

Array.from(this.el.children).forEach((el) => {
      const option = el as HTMLOptionElement;
      if (this.value.includes(option.value)) {
        option.selected = true;
        option.setAttribute('selected', 'selected'); 
      } else {
        option.selected = false;
        option.removeAttribute('selected');
      }
    });
```

You, Team, have done those updates for reasons. I prefer to let you handle this with your long term vision of the tool. I'm far from a JS developer. 😁 

I hope this helped to fix it.

**Comment by olegpix** [comment]
@brcebn Hi
The bug was fixed in v 3.2 (released 30 Jul 2025 – see changelog entry “Fixed: Advanced Select. Triggers remote API call on dropdown close [Issue #667]”).
Just upgrade to the latest Preline and the extra request on dropdown close will disappear—no extra init parameters required

**Comment by brcebn** [comment]
Thanks a lot @olegpix !

**Comment by brcebn** [comment]
Hi @olegpix 

I think this is partially fixed. 
I'm able to get it work setting a full URL and not only a relative. Also, I now have 2 search bars. 
It might be a side effect of another fix. 
What do you think? 

<img width="864" height="174" alt="Image" src="https://github.com/user-attachments/assets/1048fbea-4a29-4164-b801-b4a97040aa69" />
